---
title: "Data Analysis Project Proposal"
author:
- "STAT 420, Summer 2018"
- "Amod Augustin - NetID: amoda2"
- "Jeff Gerlach - NetID: gerlach5"
- "Yongwoo Noh - NetID: yongwoo3"
- "Naveen Vasu - NetID: nvasu2"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document: 
    toc: yes
  pdf_document: default
urlcolor: cyan
---

***

## Price Analysis and Prediction for Melbourne Housing Market

***

### Dataset Description

The dataset used in this project is a compilation of publically available housing data from Melbourne, Austrailia that had been scraped weekly from the website https://www.domain.com.au/ between January 28, 2016 and March 17th 2018 and shared on the data science/machine learning competition website https://www.kaggle.com. The user that provided the dataset also cleaned the data and provided some information from another source (namely the number of bedrooms) - there are missing values that will need to be dealt with in the data for the 34,857 listings provided. Below is a brief description of each column in the provided CSV (where each observation is a house listed for sale in Melbourne between 01/28/2016 and 03/17/2018):
 
 * Suburb: Name of Suburb in Melbourne
 * Address: Address of house that was sold
 * Rooms: Number of rooms in house that was sold
 * Type: 
    + h - house, cottage, villa, semi, terrace
    + u - unit, duplex
    + t - townhouse
 * Price: Sale price in Australian dollars (AUD)
 * Method: 
    + PI - property passed in
    + PN - sold prior not disclosed
    + S - property sold
    + SA - sold after auction
    + SN - sold not disclosed
    + SP - property sold prior
    + SS - sold after auction price not disclosed
    + VB - vendor bid
    + W - withdrawn prior to auction
 * SellerG: Real estate agent's name
 * Date: Date house was sold
 * Distance: Distance (in km) from Melbourne's central business district
 * Postcode: Postal Code
 * Bedroom2: # of bedrooms (from a different source)
 * Bathroom: # of bathrooms
 * Car: # of spots for cars
 * Landsize: Size of property (land) in meters
 * BuildingArea: Building size in meters
 * YearBuilt: Year house was built
 * CouncilArea: Governing council for the area
 * Lattitude: Latitude value
 * Longtitude: Longitude value
 * Regionname: general region (West, North, etc.)
 * Propertycount: Number of properties located in the suburb

***

### Dataset Background Information

Citation of data source:

Melbourne, Australia Housing Market data from January 2016 scraped from publically available results posted every week on Domain.com.au by Tony Pino.

https://www.kaggle.com/anthonypino/melbourne-housing-market#Melbourne_housing_FULL.csv

Released Under CC BY-NC-SA 4.0:
https://creativecommons.org/licenses/by-nc-sa/4.0/

***

### Statement of Interest

State business, science, research, or personal interest we have in the dataset that we hope to explore.

***

### Evidence Data Can Be Loaded Into `R`

```{r, message = FALSE, warning = FALSE}
library(readr)
housing = read_csv("Melbourne_housing_FULL.csv", na = "NA", col_types = cols(BuildingArea = col_number(), Landsize = col_number(), Price = col_number(), Propertycount = col_number(), Date = col_date(format = "%d/%m/%Y")))
head(housing$Price) # have not removed NA values yet
```
 
 
